// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW2uWJoYB-2P04CbU7Z2qjd0ssZYfQr2M',
    appId: '1:696560524448:web:29c35ad5d41510085cbdc5',
    messagingSenderId: '696560524448',
    projectId: 'rmk-wedding-invidatiton',
    authDomain: 'rmk-wedding-invidatiton.firebaseapp.com',
    storageBucket: 'rmk-wedding-invidatiton.firebasestorage.app',
    measurementId: 'G-07VH8P06E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8f93mFZxb9GoMNwJjw15WOCVg_ANdsv4',
    appId: '1:696560524448:android:99ebf3b42f06922c5cbdc5',
    messagingSenderId: '696560524448',
    projectId: 'rmk-wedding-invidatiton',
    storageBucket: 'rmk-wedding-invidatiton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgTZW9-AksX5XZz7h9SbLwDS8FTPj0fY',
    appId: '1:696560524448:ios:a002c4101a177d0d5cbdc5',
    messagingSenderId: '696560524448',
    projectId: 'rmk-wedding-invidatiton',
    storageBucket: 'rmk-wedding-invidatiton.firebasestorage.app',
    iosBundleId: 'com.rmk.weddingInvidatiton',
  );
}
